### ISSUE TITLE
Merging clonal evolution trees across samples...error

### ISSUE THREAD

**Issue by ramaniak** [hdng/clonevol#1]
Hello,
I am using to clonevol to visualize and am running into the following error. 

```
Finding matched clonal architecture models across samples...
Found  1 compatible model(s)
Merging clonal evolution trees across samples...
Error in data.frame(lab = v$lab, sample.with.cell.frac.ci = paste0(ifelse(v$is.founder,  : 
  arguments imply differing number of rows: 0, 1
```
I have attached the file I am using to run clonevol and have read it in as 'G.data'

here is the command that is throwing the error:
```
vaf.col.names <- grep (".vaf",colnames(G.data),value=TRUE)

x <- infer.clonal.models(variants=G.data,
cluster.col.name="cluster",
vaf.col.names=vaf.col.names,
subclonal.test = "bootstrap",
subclonal.test.model = "non-parametric", 
cluster.center = "mean",
num.boots = 1000, 
founding.cluster = 1,
min.cluster.vaf = 0.01,
p.value.cutoff = 0.05,
alpha = 1,
random.seed = 60000)

```
Thanks

[G.input_clusters.txt](https://github.com/hdng/clonevol/files/581371/G.input_clusters.txt)

**Comment by hdng** [comment]
Hi ramaniak,

The default range for VAF in clonevol is 0-100 (%), and your data is form 0-1, so you should turn off percentage mode by including "vaf.in.percent=F" in infer.clonal.models call.

Thanks.

**Comment by qindan2008** [comment]
For my data, the same error occurred, even the vaf range is 0-100 (%)
