### ISSUE TITLE
tree plot error2

### ISSUE THREAD

**Issue by xtmgah** [hdng/clonevol#10]
Hello:

I am using the plot.tree.clone.as.branch function to generate the tree. But i found there is no tree generated if the branches like this: 

> tree_data %>% select(lab,parent,branches)
   lab parent branches
1    1     13      021
2    2     14     0221
3    3     14     0222
10  10     -1        Y
5    5     16    01221
6    6     16    01222
7    7     15     0121
8    8     11     0111
9    9     11     0112
11  11     12      011
12  12     17       01
13  13     17       02
14  14     13      022
15  15     12      012
16  16     15     0122
17  17     10        0

> plot.tree.clone.as.branch(tree_data,angle = 30,node.size =0,branch.text.size = 0.5,text.angle = 0,node.text.size = 1,branch.width=0.5)
Error in x0[i] <- x1[which(x$branches == parent)] : 
  replacement has length zero

Could you let me know how to fix this? ?? 

Here is the data frame of tree_data. 
[tree_data.RData.zip](https://github.com/hdng/clonevol/files/1192005/tree_data.RData.zip)

**Comment by hdng** [comment]
Looks like your tree has many branches. I've recently updated the tree package to handle more branches. Could you update it and see if the problem still persists?

> devtools::install_github('hdng/trees')

**Comment by xtmgah** [comment]
Thanks for your reply.    I try both old one and new one in your GitHub.    Both is not working. The same error. If I combine branch 'Y' and '0' to a new '0', it working.   
  

  
  

  
  
>

**Comment by xtmgah** [comment]
So, the original node 'Y' is the outroot and '0' is first node... i guess this is the reason the code failed?
  

  
  

  
  
>

**Comment by xtmgah** [comment]
Could you help to fix this? Thanks.

**Comment by xtmgah** [comment]
I just try to put the "Y" in the first row and it totally working... So i think the program default need the "Y" trunk in the first row....
