### ISSUE TITLE
ERROR: No clonal models for sample using clonevol

### ISSUE THREAD

**Issue by gyfangel** [hdng/clonevol#13]
Hello,
I get the following error when running infer.clonal.models(). 

ERROR: No clonal models for sample: .
Check data or remove this sample, then re-run.

I have got more SNVs using about 430 or 1500 SNVs as the input data.But the error stills appears.

And CNVs infect the VAF (about 7/40 SNVs with VAF closed to 1). Then how to solve this problem? I cannot remove the 7 SNVs for their importance.
But I have input the CNV results when running sciClone.

I don't know how to choose the clonal model. So I tried both of them(polyclonal and monoclonal).
But the error still appear.

I am very confused.
And hope for your reply and help.
Thank you.
Gao

**Comment by hdng** [comment]
Duplicated, see https://github.com/hdng/clonevol/issues/12
