### ISSUE TITLE
Monoclonal Fishplot Failure

### ISSUE THREAD

**Issue by RaphaelHablesreiter** [hdng/clonevol#16]
Hello,
I have similar data to the example dataset of clonevol, but I am not able to create a FishPlot as shown in the readme-file.
The problem is that the infer.clonal.models()-function scales low vaf-values so that they are in total 100% (see figure).

![clonevol](https://user-images.githubusercontent.com/23275967/33654522-ae26f61e-da70-11e7-8a2a-550291b26258.png)

How can I change the infer.clonal.models()-function, to be able to create a FishPlot as in the example.

Thanks in advance.

**Comment by hdng** [comment]
What errors did you get? Can you send a long the data and code that produced the errors?

**Comment by RaphaelHablesreiter** [comment]
I am using this dataset:

`chromosome,position,var_1,var_2,var_3,var_4,var_5,ref_1,ref_2,ref_3,ref_4,ref_5,vaf_1,vaf_2,vaf_3,vaf_4,vaf_5,gene
2,25972650,1,1,6644,114,4882,31145,76850,13854,50258,31214,0.0032106852,0.0013012192,32.4129183335,0.2263162074,13.5250443262,ASXL2
12,112153702,20959,95,14567,682,6934,32135,150154,37966,82833,49055,39.4752702754,0.0632283742,27.7292368606,0.8166197689,12.3845755416,ACAD10
6,142764522,524,4,1,3,1,9297,14037,7636,12796,6890,5.3355055493,0.0284879994,0.0130941469,0.0234393312,0.0145116819,ADGRG6
X,129299564,8,19,8,61,2415,21218,33352,25550,34846,17284,0.0376896259,0.0569356627,17.5673495725,0.1747500501,12.2595055587,AIFM1
17,6905103,5066,3,3317,26,930,8081,24144,8526,21160,9942,38.5335057428,0.0124239036,28.0081060542,0.1227225526,8.5540838852,ALOX12
3,10157453,0,1,1,0,0,13139,14825,12578,19454,9642,0,0.0067449076,0.0079497575,0,0,BRK1
5,41172441,10264,49,5909,71,1612,12963,42747,13797,35021,14348,44.1899513497,0.1144966819,29.9857911296,0.2023253163,10.1002506266,C6
3,53769523,13105,25,8900,40,2864,15692,31408,17218,44036,21338,45.508212661,0.0795342474,34.0761160885,0.0907523369,11.8337327494,CACNA1D
1,36933434,2279,37,10,10,9,24231,52418,31217,40258,19771,8.5967559412,0.0705366505,0.0320235693,0.0248336148,0.0455005056,CSF3R
12,58217809,2,6,4190,42,859,18459,41385,18526,16690,6832,0.0108336493,0.0144959049,18.4451487938,0.2510160172,11.1688987128,CTDSP2
19,10893756,7536,2,0,1,1,23444,45542,25944,37672,36609,24.3253712072,0.0043913578,0,0.0026544209,0.0027314941,DNM2
14,102461552,15,24,6163,54,1973,18371,34379,36874,29997,13015,0.0815838138,0.069761358,14.3202360759,0.1796945193,13.1638644249,DYNC1H1
16,22278148,2,21,4,2,4,21476,94437,26428,27378,16783,0.009311854,0.0222321032,0.0151331719,0.0073046019,0.0238279621,EEF2K
3,43073828,4420,5,3202,0,1063,5621,16052,6835,17302,8197,44.0195199681,0.0311390671,31.9019627379,0,11.4794816415,FAM198A
6,82459681,10,21,1090,9,625,11267,19082,8976,16365,7243,0.0886760663,0.1099303774,10.8285316908,0.0549651887,7.9435688866,FAM46A
11,18339381,1,0,0,0,0,453,374,398,158,271,0.2202643172,0,0,0,0,HPS5
1,220276043,3464,19,1108,9,422,4557,22588,2406,13074,3161,43.1866350829,0.0840447649,31.531018782,0.0687915616,11.7778397991,IARS2
1,62329988,4,1,896,1,9,11085,4445,4893,833,147,0.0360717828,0.0224921278,15.4776299879,0.1199040767,5.7692307692,INADL
19,49573705,17920,15,2199,16,1076,22483,7092,5756,7427,7704,44.3531420934,0.2110595188,27.642991829,0.2149670832,12.2551252847,KCNA7
1,160771583,6182,9,3137,10,700,8788,8606,6938,10541,6684,41.2959251837,0.1044689495,31.1364764268,0.0947777462,9.4799566631,LY9
10,19678455,6900,71,36,34,32,108428,99901,50688,38032,34964,5.9829356271,0.0710198856,0.0709723208,0.089318552,0.0914390216,MALRD1
6,131919864,2874,16,14,4,8,21081,14421,10926,6446,2629,11.9974953037,0.110826349,0.1279707495,0.0620155039,0.3033750474,MED23
15,42019507,1618,4,1,1,1,21824,10010,12501,7622,3471,6.9021414555,0.0399440783,0.0079987202,0.0131181949,0.0288018433,MGA
8,71068547,20099,14,6645,18,717,26638,29565,13789,15184,5230,43.0044718317,0.0473308766,32.5193305276,0.118405473,12.0564990752,NCOA2
2,101611991,0,0,401,0,20,10489,8012,4692,2200,545,0,0,7.873551934,0,3.5398230088,NPAS2
2,60987309,0,0,205,0,0,5995,1687,1606,488,65,0,0,11.3197128658,0,0,PAPOLG
5,149274840,96,42,21,19,21,46539,29562,13928,16322,13444,0.2058539723,0.1418727199,0.1505484264,0.116271954,0.155959896,PDE6A
6,79656556,1099,0,278,0,7,1555,1950,639,390,58,41.4091936699,0,30.3162486369,0,10.7692307692,PHIP
6,36270121,24084,7,7950,1,566,32743,56342,16736,12328,4215,42.3812624281,0.0124225807,32.204488374,0.0081109579,11.8385275047,PNPLA1
1,204379367,1,0,121,0,2,1548,954,581,182,28,0.0645577792,0,17.2364672365,0,6.6666666667,PPP1R15B
14,70234890,43,7,31,14,575,12917,8587,13290,7404,7324,0.3317901235,0.0814521759,0.2327152616,0.1887301159,7.279402456,SRSF5
17,35825681,533,1,0,0,0,6616,3631,4249,1272,452,7.4555881942,0.0275330396,0,0,0,TADA2A
3,176756174,8265,16,2313,16,1107,11780,35490,5334,5736,8729,41.2322274882,0.0450628063,30.2471557474,0.2781641168,11.2545750305,TBL1XR1
1,32645995,2987,2,1607,6,186,4483,1173,3819,2152,1062,39.9866131191,0.170212766,29.6166605234,0.2780352178,14.9038461538,TXLNA
11,32413610,3232,1,3351,3,118,10101,10659,1819,953,333,24.2406060152,0.009380863,64.8162475822,0.3138075314,26.1640798226,WT1
19,58198532,1640,2,301,2,202,2416,3333,574,441,1694,40.4339250493,0.059970015,34.4,0.4514672686,10.6540084388,ZNF551`

and use this code to produce the plots:

`library(fishplot)
library(clonevol)
library(sciClone)

setwd("/Users/raphaelhablesreiter/Projects/FishPlot/Output")
clonevol.colors <- c('#999793', '#8d4891', '#f8e356', '#fe9536', '#d7352e')
input <- read.csv(file = "/Users/raphaelhablesreiter/Projects/FishPlot/AML_07.csv", header = TRUE, dec = ".", stringsAsFactors = FALSE, sep = ",") 
input_names <- c("Time_1", "Time_2", "Time_3", "Time_4", "Time_5")

colnames_input <- colnames(input)
#input_number <- sum(startsWith(colnames_input, "var"), na.rm = TRUE)
input_number <- length(input_names)

# ==============================================================================
# Splitting Input-File
# ==============================================================================
#chr, pos, ref_reads, var_reads, vaf

tmp <- matrix(ncol = 5, nrow = nrow(input))
tmp <- as.data.frame(tmp)
colnames(tmp) <- c("chr", "pos", "ref_reads", "var_reads", "vaf")
input_annotation <- matrix(ncol = 3, nrow = nrow(input))
colnames(input_annotation) <- c("chr", "pos", "gene_name")

tmp[,1] <- input[,1]
tmp[,2] <- as.numeric(input[,2])

for (i in 1:input_number)
{
    tmp[,3] <- as.numeric(input[[paste0("ref_",i)]])
    tmp[,4] <- as.numeric(input[[paste0("var_",i)]])
    tmp[,5] <- as.numeric(input[[paste0("vaf_",i)]])
    assign(paste0("sample_",i), tmp)
}

input_annotation[,1] <- input[,1]
input_annotation[,2] <- input[,2]
input_annotation[,3] <- input[,ncol(input)]


# ==============================================================================
# SciClone Plots
# ==============================================================================

sample_list <- vector("list", input_number)

for (i in 1:input_number)
{
    sample_list[[i]] <- get(paste0("sample_",i))
}

sc = sciClone(
    vafs = sample_list,
    sampleNames = input_names,
    annotation = input_annotation,
    useSexChrs = FALSE,
    doClusteringAlongMargins = FALSE
)

sc.plot1d(sc, "sciclone_cluster1d.pdf")
sc.plot2d(sc, "sciclone_cluster2d.pdf")  
writeClusterTable(sc, "sciclone_clusterinfo.tsv")
sciclone_out <- read.table(file = "sciclone_clusterinfo.tsv", header = TRUE, sep = "\t")

# ==============================================================================
# ClonEvol
# ==============================================================================

vaf.col.names <- grep('.vaf', colnames(sciclone_out), value=T)
sample.names <- gsub('.vaf', '', vaf.col.names)
sciclone_out[, sample.names] <- sciclone_out[, vaf.col.names] 
vaf.col.names <- sample.names

row.has.na <- apply(sciclone_out, 1, function(x){any(is.na(x))})
sciclone_out <- sciclone_out[!row.has.na,]
sciclone_out <- sciclone_out[order(sciclone_out$cluster),]

clonevol_input <- matrix(ncol = (2 + input_number), nrow = nrow(sciclone_out))
clonevol_input <- as.data.frame(clonevol_input, stringsAsFactors = FALSE)
colnames(clonevol_input) <- c("cluster", input_names, "gene")
clonevol_input[,1] <- as.numeric(sciclone_out$cluster)
for (i in 1:input_number)
{
    clonevol_input[,as.numeric(i + 1)] <- as.numeric(sciclone_out[,which(colnames(sciclone_out) == input_names[i])])
}
clonevol_input[,ncol(clonevol_input)] <- as.character(sciclone_out$gene_name)

clonevol_model <- infer.clonal.models(
    variants = clonevol_input,
    cluster.col.name = "cluster",
    model = "monoclonal",
    vaf.col.names = vaf.col.names,
    subclonal.test = "bootstrap",
    subclonal.test.model = "non-parametric",
    sample.groups = NULL,
    cluster.center = "mean",
    num.boots = 1000,
    founding.cluster = '1',
    min.cluster.vaf = 0.0001,
    p.value.cutoff = 0.0001,
    # alpha level in confidence interval estimate for CCF(clone)
    alpha = 0.01,
    random.seed = 63108,
    clone.colors = clonevol.colors,
    score.model.by = "probability",
    vaf.in.percent = TRUE
)

clonevol_model <- transfer.events.to.consensus.trees(
    clonevol_model,
    clonevol_input,
    cluster.col.name = 'cluster',
    event.col.name = 'gene')

clonevol_model <- convert.consensus.tree.clone.to.branch(
    clonevol_model, 
    branch.scale = 'sqrt')

plot.clonal.models(
    clonevol_model,
    # box plot parameters
    box.plot = TRUE,
    fancy.boxplot = TRUE,
    fancy.variant.boxplot.highlight = 'NULL',
    fancy.variant.boxplot.highlight.shape = 21,
    fancy.variant.boxplot.highlight.fill.color = 'red',
    fancy.variant.boxplot.highlight.color = 'black',
    #fancy.variant.boxplot.highlight.note.col.name = 'is.driver',
    fancy.variant.boxplot.highlight.note.color = 'blue',
    fancy.variant.boxplot.highlight.note.size = 2,
    fancy.variant.boxplot.jitter.alpha = 1,
    fancy.variant.boxplot.jitter.center.color = 'grey50',
    fancy.variant.boxplot.jitter.size = 4,
    fancy.variant.boxplot.base_size = 12,
    #size letter axis boxplot
    fancy.variant.boxplot.plot.margin = 1,
    fancy.variant.boxplot.vaf.suffix = '.VAF',
    
    # bell plot parameters
    clone.shape = 'bell',
    bell.event = TRUE,
    bell.event.label.color = 'blue',
    bell.event.label.angle = 60,
    clone.time.step.scale = 1,
    bell.curve.step = 2,
    
    
    # node-based consensus tree parameters
    merged.tree.plot = TRUE,
    tree.node.label.split.character = ',',
    tree.node.shape = 'circle',
    tree.node.size = 40,
    tree.node.text.size = 1,
    merged.tree.node.size.scale = 2,
    merged.tree.node.text.size.scale = 1,
    merged.tree.cell.frac.ci = FALSE,
    
    # branch-based consensus tree parameters
    merged.tree.clone.as.branch = TRUE,
    mtcab.event.sep.char = ',',
    mtcab.branch.text.size = 0.7,
    #size of the genes
    mtcab.branch.width = 0.5,
    mtcab.node.size = 3,
    mtcab.node.label.size = 1,
    mtcab.node.text.size = 0.5,
    #title in branched tree
    
    # cellular population parameters
    cell.plot = TRUE,
    num.cells = 100,
    cell.border.size = 0.25,
    cell.border.color = 'black',
    clone.grouping = 'random',
    #horizontal, vertical, random
    
    #meta-parameters
    scale.monoclonal.cell.frac = FALSE,
    show.score = FALSE,
    cell.frac.ci = TRUE,
    disable.cell.frac = TRUE,
    max.num.models.to.plot = 100,
    # output figure parameters
    out.dir = getwd(),
    out.format = 'pdf',
    overwrite.output = TRUE,
    width = 24,
    height = 16,
    
    # vector of width scales for each panel from left to right
    panel.widths = c(2, 1, 0.6, 1, 1.5)
)


# ==============================================================================
# FishPlot Plots
# ==============================================================================

fishplot_input <- generateFishplotInputs(clonevol_model, rescale = TRUE)


pdf("fishplot.pdf", width = 8, height = 4)
for (i in 1:length(fishplot_input$cell.fractions))
{
    
    fishplot_objects <- createFishObject(fishplot_input$cell.fractions[[i]], fishplot_input$parents[[i]])
    fishplot_layout = layoutClones(fishplot_objects)
    fishplot_layout = setCol(fishplot_layout, fishplot_input$clonevol.clone.colors)
    fishPlot(
        fishplot_layout,
        shape = "bezier",
        cex.title = 0.7,
        vlines = seq(1, length(input_names)),
        vlab = input_names,
        pad.left = 0.5
    )
}
dev <- dev.off()
`

For this I am getting three different models, where the first one looks like this:

![clonevol](https://user-images.githubusercontent.com/23275967/33671454-eef98350-daa7-11e7-8e74-37efcae420e6.png)

and the fishplot:

![fishplot](https://user-images.githubusercontent.com/23275967/33671466-fb29a8bc-daa7-11e7-9e95-3bc1a71177c9.png)

**Comment by hdng** [comment]
Okay I see what the problem is. Here is the quick dirty fix. If you insert the following code after generateFishplotInputs, it will scale the cell.frac according to VAF. 

vafs = estimate.clone.vaf(clonevol_model$variants, vaf.col.names=vaf.col.names)
scales = vafs[vafs$cluster == 1, vaf.col.names]/max(vafs[vafs$cluster == 1, vaf.col.names])
for (i in 1:length(fishplot_input$cell.fractions)){
    fishplot_input$cell.fractions[[i]] =  (fishplot_input$cell.fractions[[i]] * 
           as.matrix(scales[rep(1,nrow(fishplot_input$cell.fractions[[i]])),]))
}

You also need to change the shape param in fishPlot to "spline":

fishPlot(
        fishplot_layout,
        #shape = "bezier",
        shape = "spline",
        cex.title = 0.7,
        vlines = seq(1, length(input_names)),
        vlab = input_names,
        pad.left = 0.5
)

**Comment by RaphaelHablesreiter** [comment]
Thank you!
