### ISSUE TITLE
Input file from PhyloWGS

### ISSUE THREAD

**Issue by mauroraptor86** [hdng/clonevol#20]
In Figure 1, it is written that output from PhyloWGS can be visualized in ClonEvol.

But which PhyloWGS output file(s) is needed?

**Comment by hdng** [comment]
Ah sorry that might have made you think that clonevol can take direct output from PhyloWGS. To visualize trees generated outside of clonevol, two very simple TSV files are needed. Please see section "Vizualizing trees predicted by other tools" in the vignette. Briefly, those files are:

1) Variant assignment to clusters/clones (variants.tsv, similar to clonevol input, see AML1 example). You can produce this file for AML1 case after running through AML1 example by:
```
write.table(y$variants, file='variants.tsv', quote=F, sep='\t', row.names=F)
```

2) The tree itself (tree.tsv) with at least 3 columns: clone, parent, sample.with.nonzero.cell.frac.ci, eg. for AML1, the file should look like.
```
clone	parent	sample.with.nonzero.cell.frac.ci
1	-1	*P,*R
2	1	P
3	1	P
4	3	P
5	4	*R

```

And to produce the tree, for this case, you can run:
```
library(clonevol)
y = import.tree('tree.tsv', 'variants.tsv'  )
y = convert.consensus.tree.clone.to.branch(y, branch.scale = 'sqrt')
pdf('imported-tree.pdf', width=3, height=5, useDingbats=F)
plot.all.trees.clone.as.branch(y, branch.width = 0.5,
       node.size = 1, node.label.size = 0.5)
dev.off()
```
