### ISSUE TITLE
Pyclone, cellular_prevalence, variant_allele_frequency

### ISSUE THREAD

**Issue by zorrodong** [hdng/clonevol#21]
Dear Ha X. Dang,

Thanks for the wonderful tool. As you said, clonevol can use the results of Pyclone as input file.

The results of Pyclone include "cellular_prevalence" and "variant_allele_frequency", I wonder are these two results are the CCF and VAF as input of clonevol?

Looking forward to your reply, thanks very much!

Best, 

Zorro
2018.06.02

**Comment by hdng** [comment]
The ideal input should be copy number corrected VAF or CCF. To get these from Pyclone:

CCF = cellular_prevalence
CN corrected VAF = cellular_prevalence/2

However, uncorrected VAF may still work if copy number are random such that the center of the clusters is not heavily shifted away from true underlying cellular prevalence.

Also, make sure that your Pyclone cellular_prevalence is not barred by 100% (refer to this issue https://github.com/hdng/clonevol/issues/4)

**Comment by hdng** [comment]
Forgot to mention that if you want to use CCF directly, use ccf.col.names argument in infer.clonal.models function and ignore vaf.col.names argument.

**Comment by zorrodong** [comment]
Thanks for your prompt and kind reply. It really helps me a lot!

Best wishes!

**Comment by zorrodong** [comment]
Sorry to trouble you again.

Before, I used the uncorrected VAF, and clonevol could generate a model and a final result. However, when I took your advise, and used the corrected VAF (cellular_prevalence/2), no model could be inferred.

So can I just use the raw VAF ( the uncorrected VAF, the direct result of Pyclone) ? 

Thanks very much!

**Comment by hdng** [comment]
How do the clusters compare, side by side between uncorrected and corrected VAFs?
