### ISSUE TITLE
pyclone cellular_prevalence or just VAF for clonevol

### ISSUE THREAD

**Issue by crazyhottommy** [hdng/clonevol#3]
Hi, 
I have finished pyclone, and want to use clonevol for downstream analysis.
Should I just the cellular_prevalence or just VAF for clonevol?

Thanks!
Tommy

**Comment by hdng** [comment]
If your variants include ones in CN-altered region, you should take the CCF and divide by 2, to get "copy number adjusted VAF", and use that in clonevol. Otherwise, either way is fine.

**Comment by crazyhottommy** [comment]
Thanks! I will use the cellular_prevalence/2.

**Comment by immuneAI** [comment]
Hi @crazyhottommy 
Could you explain or example of your code you used in using clonevol with pyclone output, this would be a great help.
